/*
Custom License for kfoozminus Projects
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// PodjennyListerExpansion allows custom methods to be added to
// PodjennyLister.
type PodjennyListerExpansion interface{}

// PodjennyNamespaceListerExpansion allows custom methods to be added to
// PodjennyNamespaceLister.
type PodjennyNamespaceListerExpansion interface{}
