/*
Custom License for kfoozminus Projects
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/kfoozminus/booklist-crd/pkg/apis/corejenny/v1"
	scheme "github.com/kfoozminus/booklist-crd/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PodjenniesGetter has a method to return a PodjennyInterface.
// A group's client should implement this interface.
type PodjenniesGetter interface {
	Podjennies(namespace string) PodjennyInterface
}

// PodjennyInterface has methods to work with Podjenny resources.
type PodjennyInterface interface {
	Create(*v1.Podjenny) (*v1.Podjenny, error)
	Update(*v1.Podjenny) (*v1.Podjenny, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Podjenny, error)
	List(opts metav1.ListOptions) (*v1.PodjennyList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Podjenny, err error)
	PodjennyExpansion
}

// podjennies implements PodjennyInterface
type podjennies struct {
	client rest.Interface
	ns     string
}

// newPodjennies returns a Podjennies
func newPodjennies(c *CorejennyV1Client, namespace string) *podjennies {
	return &podjennies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the podjenny, and returns the corresponding podjenny object, and an error if there is any.
func (c *podjennies) Get(name string, options metav1.GetOptions) (result *v1.Podjenny, err error) {
	result = &v1.Podjenny{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podjennies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Podjennies that match those selectors.
func (c *podjennies) List(opts metav1.ListOptions) (result *v1.PodjennyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.PodjennyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podjennies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested podjennies.
func (c *podjennies) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("podjennies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a podjenny and creates it.  Returns the server's representation of the podjenny, and an error, if there is any.
func (c *podjennies) Create(podjenny *v1.Podjenny) (result *v1.Podjenny, err error) {
	result = &v1.Podjenny{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("podjennies").
		Body(podjenny).
		Do().
		Into(result)
	return
}

// Update takes the representation of a podjenny and updates it. Returns the server's representation of the podjenny, and an error, if there is any.
func (c *podjennies) Update(podjenny *v1.Podjenny) (result *v1.Podjenny, err error) {
	result = &v1.Podjenny{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podjennies").
		Name(podjenny.Name).
		Body(podjenny).
		Do().
		Into(result)
	return
}

// Delete takes name of the podjenny and deletes it. Returns an error if one occurs.
func (c *podjennies) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podjennies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *podjennies) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podjennies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched podjenny.
func (c *podjennies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Podjenny, err error) {
	result = &v1.Podjenny{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("podjennies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
