/*
Custom License for kfoozminus Projects
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/kfoozminus/booklist-crd/pkg/client/clientset/versioned/typed/kfoozminus.com/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKfoozminusV1 struct {
	*testing.Fake
}

func (c *FakeKfoozminusV1) Podjennies(namespace string) v1.PodjennyInterface {
	return &FakePodjennies{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKfoozminusV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
