/*
Custom License for kfoozminus Projects
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	corejennyv1 "github.com/kfoozminus/booklist-crd/pkg/apis/corejenny/v1"
	versioned "github.com/kfoozminus/booklist-crd/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kfoozminus/booklist-crd/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/kfoozminus/booklist-crd/pkg/client/listers/corejenny/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodjennyInformer provides access to a shared informer and lister for
// Podjennies.
type PodjennyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.PodjennyLister
}

type podjennyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodjennyInformer constructs a new informer for Podjenny type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodjennyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodjennyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodjennyInformer constructs a new informer for Podjenny type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodjennyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CorejennyV1().Podjennies(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CorejennyV1().Podjennies(namespace).Watch(options)
			},
		},
		&corejennyv1.Podjenny{},
		resyncPeriod,
		indexers,
	)
}

func (f *podjennyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodjennyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podjennyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&corejennyv1.Podjenny{}, f.defaultInformer)
}

func (f *podjennyInformer) Lister() v1.PodjennyLister {
	return v1.NewPodjennyLister(f.Informer().GetIndexer())
}
