apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appscrds.corejenny
spec:
  group: corejenny
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: appscrds
    singular: appscrd
    kind: AppsCRD
    listKind: AppsCRDList
    shortNames:
    - acrd

